### ISSUE TITLE
Problem with disparity levels greater than 33

### ISSUE THREAD

**Issue by puglial** [reisub/SemiGlobal-Matching#1]
Hi, when i try to use the following command I get segmentation fault:
./sgm test/teddy/left.png test/teddy/right.png prova.png 34

This happens for every disparity levels greater than 33, using 33 or less works fine, any hint?

**Comment by reisub** [comment]
I'm not sure, I don't remember ever testing it with a disparity level greater than 32.
You might be able to find a problem using a debugger such as gdb (you will need to compile using -g flag with gcc for that to work).

This was a school project which I don't have plans or the time to maintain so you're on your own for this. Good luck!

**Comment by puglial** [comment]
There were a huge memory leak in function calculatePixelCostOneWayBT, i have fixed it if you are interested

**Comment by reisub** [comment]
Cool!

Would you care to make a pull request? You might save someone a lot of time in the future.

**Comment by puglial** [comment]
done it!
